### ISSUE TITLE
Create an authentication component

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#10]
We'll need a standard connect component for users to auth into our app.

This should leverage ConnectKit.

A pull request with this feature should include:

- [ ] A minimal `Connect` CTA
- [ ] ENS resolution for the connected address
- [ ] Hover state or click which reveals a `Disconnect` CTA
- [ ] Bump ConnectKit to `1.5.2`

**Comment by salieflewis** [comment]
To avoid ambiguity we should probably just mock this out in Figma.

cc: @ioeylim

**Comment by ioeylim** [comment]
![Image](https://github.com/1ifeworld/river/assets/113192435/0e092443-27a9-4581-947f-a1a526af0dd9)

Link to [Figma](https://www.figma.com/file/vq8D56Fddhysfv24raCmL1/River?type=design&node-id=41%3A4856&mode=design&t=mznUGevER3zvdUWD-1)
