### ISSUE TITLE
Unable to add createdBy and createdAt (listing level) to frontend query

### ISSUE THREAD

**Issue by 0xTranqui** [1ifeworld/river#101]
After updating the ponder schema and confirming channel level createdBy + listing level createdAt where populating the database correctly, we were unable to update the frontend query + codegen. Getting errors like it was unable to detect those values existed. This is preventing us from correctly showing the channel creator address, and sorting channel listings chronologically

cc @salieflewis curious if u could glance at this whenever u get the chance. assuming that we just doing something stupid at the regeneration of the frontend sdk, however we were following all the steps including typing out the DocumentNode thing

**Comment by 0xTranqui** [comment]
cc @jawndiego too

**Comment by salieflewis** [comment]
Linked #102
