### ISSUE TITLE
Decide upon an icon library

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#11]
In order to avoid having to create a whole icon set from scratch, I propose we lean on an existing one that should cover most if not all of our use cases. This will help create standardization across the design.

Here are a few that I recommend/have used in the past.

1. https://www.radix-ui.com/icons

2. https://phosphoricons.com/

3. https://lucide.dev/

cc: @ioeylim

**Comment by ioeylim** [comment]
Will look into this

**Comment by ioeylim** [comment]
![Image](https://github.com/1ifeworld/river/assets/113192435/ed0bbaca-38df-442b-9e3f-31d9c2ab6485)

Organized a small set of icons from radix. Probably will need more, but think this covers most. Is it annoying to have 1-2 custom icons? (mostly because I couldn't find the right ones)

**Comment by salieflewis** [comment]
I believe Radix icons are 15x15, so as long as our custom ones are the same and look/feel like they fit in, it is not annoying at all!

**Comment by ioeylim** [comment]
Ok, will make sure the icons fit the 15x15 dimension
