### ISSUE TITLE
UserID Registration: Validate name exist in DB before pushing transactions 

### ISSUE THREAD

**Issue by jawndiego** [1ifeworld/river#111]
- [ ] query getname endpoint to check if name exist 
- [ ]  if name exist return server side error to client 
- [ ]  add validate function to register and delegate flow before we push transactions
- [ ] on success return name and id have been registered

**Comment by salieflewis** [comment]
Can you also just generally summarize here the relationship between the validation schemas that exist on the client and those on the server? That's the gap that is missing in my knowledge.

**Comment by 0xTranqui** [comment]
<img width="1040" alt="Screenshot 2023-11-20 at 1 12 22 PM" src="https://github.com/1ifeworld/river/assets/93691906/f700d763-41dc-4c1d-9774-294c10eaca6a">
also want to call out this example from the farcaster spec repo about the other types of validation checks well want to add to our set flow

**Comment by jawndiego** [comment]
addressed in PR#114
