### ISSUE TITLE
Add interactivity to channel cards

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#117]
Relies on #116 

Channel cards likely need a hover state to indicate that they can be clicked on/further navigation can take place.

Not sure where this is documented.

Similarly we'll also need a focus state or active state for mobile (correct me if I'm wrong about this) to accomplish the same thing, where hover is not available.

- [ ] Click on a channel's cover image and be brought to its corresponding page
- [ ] Click on an individual piece within a channel and be brought to its corresponding view page

**Comment by ioeylim** [comment]
Channel card hover states are [here](https://www.figma.com/file/vq8D56Fddhysfv24raCmL1/River?type=design&node-id=41%3A4749&mode=design&t=6iebjXo1pwyLSVbj-1). Envisioning eventually a small drop down menu that you can access via the horizontal dots (···) with actions like share (twitter, copy channel link, etc), add to channel ▸(add this channel to another channel), edit channel, see members, etc. 

My guess is that for mobile there is no focus/active state? It's just clicking into the channel and into the pieces?

**Comment by salieflewis** [comment]
The navigation elements of this issue have been resolved, still need to mock out the other interactions however.
