### ISSUE TITLE
Construct the layout component for view pages

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#118]
Not exactly sure what the individual componentry within a view page will be, but we'll certainly need:

- [ ] An image component, probably `AspectRatio` from shadcn/Radix
- [ ] Title
- [ ] Creator
- [ ] Description

I imagine that the text details outlined above would be constructed similarly to how the `ChannelBanner` component was made.

**Comment by 0xTranqui** [comment]
@salieflewis your use of the word "layout" is confusing to me since it has another meaning in next13 app router speak. can you please clarify.

also are you suggesting we tap this shadcn [component](https://ui.shadcn.com/docs/components/aspect-ratio) to be our go to display content (I guess it can work for video too theoretically?) comp?

**Comment by 0xTranqui** [comment]
oh AspectRatio is just for images. got it. also wont this be problematic because it uses next/image so I cant actually add this to our design system? but maybe its fine cuz ill just improt the Card skeleton and pass AspectRatio in as a prop?
@salieflewis

**Comment by salieflewis** [comment]
That's fair, yeah this issue is meant to encompass both the App Router `Layout` component and the other components laid out in the first comment. I should have been more specific.

**Comment by salieflewis** [comment]
> oh AspectRatio is just for images. got it. also wont this be problematic because it uses next/image so I cant actually add this to our design system? but maybe its fine cuz ill just improt the Card skeleton and pass AspectRatio in as a prop? @salieflewis

I don't think the `Card` skeleton in Estuary will be relevant here.

**Comment by 0xTranqui** [comment]
> > oh AspectRatio is just for images. got it. also wont this be problematic because it uses next/image so I cant actually add this to our design system? but maybe its fine cuz ill just improt the Card skeleton and pass AspectRatio in as a prop? @salieflewis
> 
> I don't think the `Card` skeleton in Estuary will be relevant here.

good point

**Comment by salieflewis** [comment]
Completed
