### ISSUE TITLE
Create a fallback image for unsupported media

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#120]
<img width="977" alt="CleanShot 2023-09-05 at 14 50 25@2x" src="https://github.com/1ifeworld/river/assets/37086973/cb3f4df3-2f29-4b52-b488-63097330838a">

We should be able to slot in a placeholder here when media is not rendering correctly. This would be nice cause it looks really janky without it.

cc: @ioeylim

**Comment by ioeylim** [comment]
When the media is not rendering, is it also not rendering the title/creator of the piece?

**Comment by salieflewis** [comment]
> When the media is not rendering, is it also not rendering the title/creator of the piece?

I'm unclear on this, perhaps if we were providing a fallback image it then would go on and render the title and creator. I can provide more insight once I get closer to it.

**Comment by 0xTranqui** [comment]
I believe the stuff you are seeing are instances of invalid ipfs metadata (ex: ipfs string invalid or not processed correctly), which to Salief's point I think is also leading to unproper indexing of the piece title + creator fields misisng

**Comment by ioeylim** [comment]
<img width="259" alt="Screenshot 2023-09-05 at 4 34 51 PM" src="https://github.com/1ifeworld/river/assets/113192435/45ab8084-eb79-4a29-95ce-b32ad12b68fb">

**Comment by salieflewis** [comment]
> <img alt="Screenshot 2023-09-05 at 4 34 51 PM" width="259" src="https://user-images.githubusercontent.com/113192435/265819992-45ab8084-eb79-4a29-95ce-b32ad12b68fb.png">

Can you please attach the link to where this is in Figma as well.

**Comment by ioeylim** [comment]
Link to[ figma](https://www.figma.com/file/vq8D56Fddhysfv24raCmL1/River?type=design&node-id=41%3A4749&mode=design&t=6iebjXo1pwyLSVbj-1)

I need to clean up the variants in the figma, but don't think that should be a blocker for now.

**Comment by salieflewis** [comment]
Our current approach is to filter out listings that don't contain an ipfs cid.
