### ISSUE TITLE
Add hover state to title/creator text on channel cards

### ISSUE THREAD

**Issue by ioeylim** [1ifeworld/river#128]
A simple underline hover state which: 
1. If you hover over the title of the channel/piece, it takes you to the channel/piece as it would clicking on the cover image
2. If you hover over the creator of the channel/piece, it would open a modal that shows the members of that channel? (not sure about what we would direct to when it's an piece and only has one creator)

**Comment by salieflewis** [comment]
I don't think hover states should invoke route changes. Is that what you're suggesting?

I think for number two we talked about a tooltip type behavior similar to what is shown below. If so, I'm down to explore that further.

<img width="525" alt="CleanShot 2023-09-05 at 22 43 04@2x" src="https://github.com/1ifeworld/river/assets/37086973/1d6331bb-0b09-4639-a41e-a2f9354dbe38">

**Comment by ioeylim** [comment]
Yes to number two

To clarify the first point: I was suggesting allowing the titles of channels/pieces to be also clickable(with an underline hover state) the same way you would be able to with clicking on its cover image. Not sure if this invokes a route change?

**Comment by salieflewis** [comment]
Resolved #172 

Part two of the issue was split into #173
