### ISSUE TITLE
Build out a fully functional Channel page

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#131]
`ChannelBanner`
- [ ] Display other channel participants
- [ ] Determine the final styling and hover state for the Add (to Channel) button
- [x] Connect the Add (to Channel) button to the `UploadDialog`, the dialog needs to be context aware such that uploaded items get added to the appropriate Channel

`ChannelItems`
- [x] Add file types to the item list
- [ ] Add a notice on when the Channel was last updated
- [x] Discuss the functionality of the popover menu

**Comment by 0xTranqui** [comment]
@salieflewis can we close this or no

**Comment by salieflewis** [comment]
Going to close this as not planned given there is a lot in flux and probably makes sense to just create smaller issues with the remaining bullet points.
