### ISSUE TITLE
Add type for `queryResult` in the `ListingView` component

### ISSUE THREAD

**Issue by jawndiego** [1ifeworld/river#141]
should be listingsExtended, there are currently some errors that need to be addressed so it's properly typed in:

apps/frontend/app/channel/[contract]/[id]/page.tsx
line 29

**Comment by jawndiego** [comment]
also fix:
listings: any[]; // You can replace 'any' with the actual type of your listings
apps/frontend/components/listing/ListingView.tsx

**Comment by salieflewis** [comment]
Resolved #175
