### ISSUE TITLE
Modify the typography component to be consistent with the designs

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#15]
#12 introduced a typography component that we had written for the Assembly Press demo, I'm not certain exactly which styles we will need for River. It would be great to narrow this down and update the component accordingly.

**Comment by ioeylim** [comment]
started putting some down [on figma ](https://www.figma.com/file/vq8D56Fddhysfv24raCmL1/River?type=design&node-id=2%3A6&mode=design&t=mznUGevER3zvdUWD-1)

went thru the current design, and it looks like it's like maybe max 4 styles.

**Comment by salieflewis** [comment]
Ok bet. Let me know when they are good to go! From what I just checked it looks like 6, so not sure if you're continuing to add more.

Also are you married to the fractional pixels? I'm attaching the Tailwind defaults which can certainly be changed, but just wanted to shared as a template.

https://tailwindcss.com/docs/font-size

We want to be using rem, so the fractional pixels give us a bit of an ugly value.

**Comment by ioeylim** [comment]
![Image](https://github.com/1ifeworld/river/assets/113192435/43ea9b69-8a36-4d83-93ff-eabc91174224)

Updated the styles using the tailwind template. Let me know if I'm not understanding this correctly.
