### ISSUE TITLE
Fix the remaining inconsistency where new channels don't always appear after a successful transaction

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#161]
If you spam create channel, while looking at the Vercel logs on the production deploy, you'll notice that there are couple GET and POST requests that simultaneously error out. There isn't much context in these errors, so need to do some further digging to debug this.

**Comment by 0xTranqui** [comment]
@salieflewis I feel like we can close this exact issue? and then maybe open up others re error handling?

**Comment by salieflewis** [comment]
> @salieflewis I feel like we can close this exact issue? and then maybe open up others re error handling?

I agree.
