### ISSUE TITLE
Surface a work's title, creator, and description on the view pages

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#177]
<img width="379" alt="CleanShot 2023-09-11 at 17 36 10@2x" src="https://github.com/1ifeworld/river/assets/37086973/50ea40d1-c1fe-48a6-9f14-8074c77a62fc">

**Comment by salieflewis** [comment]
Does "210 channels" (as shown in the screenshot) represent how many channels this work is a part of?

Is it fair to say that we're not going to include this information for Wednesday?

cc: @1ifeworld/core

**Comment by ioeylim** [comment]
Yes and yes

**Comment by 0xTranqui** [comment]
@salieflewis assinging htis one to myself as part of me finsihing the view page work I started but if someone else wants to take it feel free
