### ISSUE TITLE
Update the channel page to the latest designs

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#181]
Can you please specify here what needs to be done @ioeylim 

Remaining as of 9/16/23

- [x] Adjust the font size for the members list to `Headline`
- [ ] Create a bounding box for the description

**Comment by ioeylim** [comment]
1. current font size for title (35px) feels too big, so adjusting the 2xl to 26px. 
2. the font size for the members lists ("junghwan.eth + 4 others") now also to 26px.
3. create a bounding box for the description, and bring the general position more up (not sure if this is the best way to describe it, so feel free to ask if it's not clear what I'm saying). 
4. drop shadow for the channel/item cards (globally).
5. new icons, but will need a bit more time to finalize.

**Comment by salieflewis** [comment]
Resolved #283
