### ISSUE TITLE
Add an IPFS service

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#184]
We'll most likely want to lean on the [web3.storage ](https://web3.storage/)API for this.

This IPFS service will be responsible for uploading the images to serve as the cover of channels.

It will also be responsible for the associated channel metadata.

This could probably be fleshed out a bit more.

cc: @jawndiego @0xTranqui

**Comment by salieflewis** [comment]
Resources:

https://github.com/ourzora/nouns-builder/tree/main/packages/ipfs-service
https://github.com/public-assembly/flexible/blob/main/hooks/useWeb3Storage.ts

There are more too if whomever is assigned this is interested in more approaches.

**Comment by salieflewis** [comment]
We'll also need to determine what the appropriate limitations are for file sizes and types.

**Comment by salieflewis** [comment]
Include a loading state for the media uploads.

**Comment by jawndiego** [comment]
upload image to ipfs -> get cid -> insert into contract uri format (name, description, image (ipfs://${cid)) -> convert cid to link -> set as channel image.

**Comment by salieflewis** [comment]
Resolved #189
