### ISSUE TITLE
Integrate the Lanyard API to generate merkle roots for access control

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#185]
We'll need to be able to generate Merkle roots based on a combination of addresses and ENS names. This will also require configuring cross chain ENS resolution #67

The default input for access control will be a Merkle root based on the connected wallet's address.

Further additions of channel members will require us to ping the Lanyard API for a new Merkle root based on the newly included addresses.

We should also finalize designs and language around this popover component.

cc: @ioeylim @0xTranqui

**Comment by ioeylim** [comment]
Yep sounds good

**Comment by jawndiego** [comment]
https://github.com/public-assembly/pass/blob/main/client/src/lanyard/getLanyardTree.ts

**Comment by jawndiego** [comment]
not closing this until we have full ENS resolution

**Comment by salieflewis** [comment]
Resolved #265
