### ISSUE TITLE
Include a success state for successfully creating a channel

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#186]
1. Add the name of the newly created channel to the sidebar

2. Take the user to the new route of their channel

**Comment by 0xTranqui** [comment]
assigning to myself as part of setting up the smart contract interactions for creating a channel.

will require a use wait for transaction that listens for the return of the "setupPress" call, and automatically routes that user to that channel/address. will need to add in a way to wait until that address has been populated in our backend

**Comment by ioeylim** [comment]
<img width="1644" alt="Screenshot 2023-09-12 at 11 06 17 PM" src="https://github.com/1ifeworld/river/assets/113192435/f32b85fc-2e27-4d34-8c5c-fec301cc6fa7">

the full creation flow is [here](https://www.figma.com/file/vq8D56Fddhysfv24raCmL1/River?type=design&node-id=520%3A1413&mode=design&t=wX2gmsnBRU0BRjv2-1)
