### ISSUE TITLE
Add biome to handle linting and formatting

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#19]
The one downside to this is that Rome doesn't support prettier plugins, aka no Tailwind classname auto reorgs. I think we can live without it.

**Comment by salieflewis** [comment]
Looks like Rome shuttered and the community fork is now called Biome

https://github.com/biomejs/biome

**Comment by salieflewis** [comment]
Inspo: https://github.com/farcasterxyz/hub-monorepo/blob/main/package.json

**Comment by 0xTranqui** [comment]
biome gang

**Comment by salieflewis** [comment]
Opened a discussion cause this shit is extra and the hub monorepo example is confusing.

https://github.com/biomejs/biome/discussions/280

**Comment by salieflewis** [comment]
Resolved #230 

Just added biome to the `frontend` repo. Probably should add the same config to the estuary docs, but not worrying about that for now.
