### ISSUE TITLE
Create a consistent way to implement icons in our design system

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#196]
References:

https://github.com/svg/svgo

**Comment by 0xTranqui** [comment]
have we not already done this with the icons folder in estuary? those seem to be working nicely

**Comment by salieflewis** [comment]
We're unable to appropriately pass in hex values as fills, so this means they won't be able to flip over when we introduce dark mode.

Also the sizing specs are kinda all over the place.
