### ISSUE TITLE
Media Handler Refactor

### ISSUE THREAD

**Issue by jawndiego** [1ifeworld/river#198]
we need to refactor our media handling routes. i.e the way we send different media types to DB, how our media component architecture works, how we identify non IANA mimeTypes, etc.

**Comment by salieflewis** [comment]
Asking the same of this, can you break this down into more actionable steps please.

cc: @jawndiego

**Comment by jawndiego** [comment]
this is a long term goal, i'm closing this at the moment as it is fairly low priority. would likely require some server-side magic number mime-type identification. but this requires more research
