### ISSUE TITLE
Determine how to disclose the contents of the `Sidebar` on mobile

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#206]
On mobile we'll use a sheet or drawer component to replace the `Sidebar`, but because the sidebar is persistent on desktop, there is no existing way in the UI to trigger it.

We'll need to a way to toggle the opening of this component. As far as closing goes I think we can get away with a touch gesture.

cc: @ioeylim

**Comment by ioeylim** [comment]
probably just what flexible did? a plus icon on the right?

**Comment by salieflewis** [comment]
> probably just what flexible did? a plus icon on the right?

Hmm ok, will do some brainstorming.

**Comment by salieflewis** [comment]
Resolved #262
