### ISSUE TITLE
Fix cors origin errors for Mux uploads

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#212]
[Here](https://www.mux.com/blog/what-are-react-server-actions) is an article re: using Mux and server actions

In the example they use the Uploads API versus the Assets API, and it looks like `cors_origin` isn't a field on the object expected with the latter.

[Here](https://docs.mux.com/guides/make-api-requests#cors-and-client-side-api-requests) are docs around why the error is popping up. We can get around the suggestions they're making because we're using server actions, but it looks like we still need to configure something regardless.

**Comment by jawndiego** [comment]
closing pending #244
