### ISSUE TITLE
Add a getting started section for local development

### ISSUE THREAD

**Issue by jawndiego** [1ifeworld/river#228]
when cloning river for the first time. a dev may encounter several hurdles:

- pnpm-lock seems to be outdated, so we need to delete and run `pnpm i` fresh
- after installing turbo globally and run `pnpm run dev` in root both the backend/frontend generated.sdk are not being generated.
which forces the user to go into apps/frontend and apps/backend and run `pnpm codegen` to generate them before they can go back to root and run `pnpm run dev`

**Comment by salieflewis** [comment]
If you want to weigh in at all on your experience here @tangerine-orange that would be helpful!

**Comment by tangerine-orange** [comment]
I think @jawndiego addressed all the issues I faced setting it up. I can take this issue if you want.

**Comment by salieflewis** [comment]
> I think @jawndiego addressed all the issues I faced setting it up. I can take this issue if you want.

https://github.com/1ifeworld/river/issues/247#issuecomment-1722505022

cc: @tangerine-orange
