### ISSUE TITLE
Add channel index to view pages

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#234]
- [ ] Ability to navigate between items by clicking on the name of the item

How should we indicate that a current item on the index is the one the user is currently navigated to?

What happens to this index on mobile?

How do we indicate to the user on mobile that they can navigate between items by tapping?

cc: @ioeylim

**Comment by 0xTranqui** [comment]
@salieflewis can I close this?

**Comment by salieflewis** [comment]
Resolved #257
