### ISSUE TITLE
Create a card component for the grid view

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#25]
This card component should be able to be reused by both channel cover images and token level images.

Do cards have a hover state? cc: @ioeylim 

What other variants do we want to include in this component? The ability to adjust border radiuses? Default sizes (sm | md | lg)?

I'll begin this by leaning on shadcn for the base and see where that gets me.

Does this card component extend to preview images like for uploading media or displaying smaller versions of channel cover images in the sidebar?

**Comment by ioeylim** [comment]
Link to Figma [here](https://www.figma.com/file/vq8D56Fddhysfv24raCmL1/River?type=design&node-id=3%3A365&mode=design&t=dxUjeIGiGUVzCbJT-1)

Will put a hover state on the channel page. 

Regarding other variants, I think stuff like border radiuses/sizes will be good. Not sure about preview images and the sidebar (just haven't really mocked this yet).

**Comment by salieflewis** [comment]
Resolved #25
