### ISSUE TITLE
Add a footer component

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#265]
Think it makes sense for the footer to appear on every route but `/item`. Therefore it might be tough to put this in the root layout.

Rough design is here:

![CleanShot 2023-12-21 at 10 57 07@2x](https://github.com/1ifeworld/river/assets/37086973/bd44279f-99a7-47ed-8fa4-dce50563f8ed)

**Comment by ioeylim** [comment]
Yeah with the way that we generally have the view pages designed currently, I think footer everywhere minus `/item` makes sense to me. 

But I'll keep that in mind when I go back to the view page designs.
