### ISSUE TITLE
first pass at Ponder CRUD

### ISSUE THREAD

**Issue by jawndiego** [1ifeworld/river#33]
- [x] Id Registry
- [x] Node Registry
- [x] Delegate Registry 
- [x] River Validator 
- [ ] Light Account (factory contract)

**Comment by salieflewis** [comment]
I'll work on what the setup for indexing the `LightAccount` looks like, the Ponder stuff here is related to [this issue](https://github.com/1ifeworld/light-account/issues).

**Comment by salieflewis** [comment]
Gist is [here](https://gist.github.com/salieflewis/01874dc77361bb9f98b28c6be2512912).
