### ISSUE TITLE
Fix layout shift caused by `PrivyProvider` not being ready 

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#355]
The marquee and header jump because the `User` component relies on Privy for its state.

**Comment by salieflewis** [comment]
This actually leads to a larger question, if we should in fact create a login page or some type of intermediary state that covers the screen before redirecting folks to what we call the homepage. Here is a loom that shows how a variety of folks are tackling this, notably Courtyard, Sona, and Friend Tech. I'm unsure how Zora does it, cause I haven't logged in there with Privy. Although maybe all accounts are subject to this now.

https://www.loom.com/share/4f4457d2a4194fa89c52ea1e11378f21

cc: @ioeylim

**Comment by 0xTranqui** [comment]
> The marquee and header jump because the `User` component relies on Privy for its state.

cant this be solved by just showing placeholder info at the beginning?

**Comment by 0xTranqui** [comment]
> some type of intermediary state that covers the screen before redirecting folks to what we call the homepage

am generally against this bc it feels like can create a more closed feeling than otherwise ncessary / stop ppls momentum

**Comment by salieflewis** [comment]
> > some type of intermediary state that covers the screen before redirecting folks to what we call the homepage
> 
> am generally against this bc it feels like can create a more closed feeling than otherwise ncessary / stop ppls momentum

It is definitely not the only solution, what would you suggest as a placeholder?

**Comment by salieflewis** [comment]
Resolved #364
