### ISSUE TITLE
QA for sizing/positioning 

### ISSUE THREAD

**Issue by ioeylim** [1ifeworld/river#395]
- [x] Update [header sizing](https://imgur.com/a/ojJFCTp)
- [x] Update Item viewpage information [line height to 7px ](https://imgur.com/a/zhjfVuD)
- [x] Update more [accurate spacing](https://imgur.com/a/VKOlw8G) in the Channel page (Name / Description / "Add an item" / Item) 
- [x] Update homepage [card positioning](https://imgur.com/a/zpJpFRl)
- [x] Update [line height](https://imgur.com/a/lSNhGQ5) 
- [x] Update mobile [item thumbnail](https://imgur.com/a/zejykar) size from 40px → 48px
- [x] Update mobile card [sizing/positioning](https://imgur.com/a/X3XPfKa)

cc: @salieflewis

**Comment by ioeylim** [comment]
@salieflewis updated this issue so that it's only sizing/positioning related tasks.

**Comment by salieflewis** [comment]
> @salieflewis updated this issue so that it's only sizing/positioning related tasks.

Thank you
