### ISSUE TITLE
UX stuff

### ISSUE THREAD

**Issue by ioeylim** [1ifeworld/river#396]
- [ ] Full page dropzone in channel pages
- [ ] Font leading (-2.5%) is not being applied on Safari
- [ ] Show channels with recent activity in the "Recent channels" list

**Comment by ioeylim** [comment]
@1ifeworld/core should I make these all separate issues?

**Comment by salieflewis** [comment]
> @1ifeworld/core should I make these all separate issues?

Please, and just make sure they're not duplicates of existing issues.
