### ISSUE TITLE
Build out our readme in order to complete quest one

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#4]
I'll leave a link to further details pertaining to quest one [here](https://docs.100.builders/builders-area/quests/main-quest)

cc: @lifew0rld/core

**Comment by ioeylim** [comment]
Submit your week 1 update before Sunday, Aug 27th 23:59 PT / Aug 28th 02:59 AM

Here is the [link](https://airtable.com/shruM3AlT8bQg8INq)

**Comment by salieflewis** [comment]
What have you shipped this week?

Our goal this week was to ship a working channel. Channels are mechanisms for referencing onchain information (think other NFTs or other channels). At the start of the week we scoped out the basic feature-set we would need to bring this to life. Our entire organization repo was empty, and now we've configured a monorepo with frontend and backend applications, as well as a separate contracts repository where we've experimented with completely new mechanisms for facilitating channel interactions.

**Comment by 0xTranqui** [comment]
Just did a first pass at week 1 full submisison. I think we can use some of saliefs language above ^ to add more color to the "what weve shipped section" I wrote in the notion. still depends on what we are actually shipping tho. here's notion [link](https://www.notion.so/lifeworld/Week-1-3ed5b7c86ca84342b27c86cc2fa967c2)

**Comment by salieflewis** [comment]
Submitted by Jawn
