### ISSUE TITLE
Redirect users to newly created channels

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#429]
When routing to channels, we currently use cids which are calculated using the `messageToCid` helper located in scrypt. In order to precompute those cids (which are treated as channel id's) we'll need to use that `messageToCid` helper in the site, most likely in `processCreateChannelPost`. In addition to calling the `revalidationHelper` we can redirect to `/channel/{resultOfMessageToCid}`.

Other things to keep in mind.

However we choose to update routing (potentially moving to sqids) will need to be replicated here.

**Comment by ioeylim** [comment]
Resolved with #566
