### ISSUE TITLE
Combine the postgres instance and ponder apps on railway

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#44]
I don't believe we don't need two separate Railway projects (currently abject-reading and maddening-board). These can both live in the same place, side by side. So all the permissions and participants can be in one place. Also we should rename the overall project to something more fitting when this is done.

**Comment by jawndiego** [comment]
thanks for pointing that out. both projects have no been merged into one project named 'River' 

<img width="1442" alt="Screen Shot 2023-08-28 at 12 45 12 PM" src="https://github.com/1ifeworld/river/assets/62079777/6f9fbfe2-a334-4dd8-8319-7ed2cfc9feaf">
