### ISSUE TITLE
Update the marquee text to show 10 most recent items that got added to channels

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#442]

**Comment by 0xTranqui** [comment]
<img width="770" alt="Screenshot 2024-02-07 at 1 06 11 PM" src="https://github.com/1ifeworld/river/assets/93691906/27d72783-cd01-420d-b244-463d5a34f41d">
i feel like it would be cool if the loop started with the "welcome to river" (and maybe the "total" counts for the day/overall?), and then got into the most recent 10 items. what yall think @salieflewis @ioeylim

**Comment by ioeylim** [comment]
> <img alt="Screenshot 2024-02-07 at 1 06 11 PM" width="770" src="https://private-user-images.githubusercontent.com/93691906/303091303-27d72783-cd01-420d-b244-463d5a34f41d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNTgxNjEsIm5iZiI6MTcwNzM1Nzg2MSwicGF0aCI6Ii85MzY5MTkwNi8zMDMwOTEzMDMtMjdkNzI3ODMtY2QwMS00MjBkLWIyNDQtNDYzZDVhMzRmNDFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDAyMDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZWMxNDE4ZGFlNTQxOTgwOGM0OTIxN2M5M2NjNWUzZjNiZTk2NjQ3NDU3ZjBkNWMzNTBhY2ExY2QxMmVhMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VBshXUFdk47l6EXYkY---Yg-k1Yi7A9fTQODqNyibOw"> i feel like it would be cool if the loop started with the "welcome to river" (and maybe the "total" counts for the day/overall?), and then got into the most recent 10 items. what yall think @salieflewis @ioeylim

Yeah I like "Welcome to River  –  IMG_6620.HEIC added to Metallic Objects  –  Voice_note11212023.mp3 added to SPAM"

**Comment by ioeylim** [comment]
Completed with #559
