### ISSUE TITLE
Add error messaging for items that are 200MB+ 

### ISSUE THREAD

**Issue by ioeylim** [1ifeworld/river#451]
![Frame 2226](https://github.com/1ifeworld/river/assets/113192435/05bd17c7-444d-42de-a889-97624b63e320)
![Frame 2227](https://github.com/1ifeworld/river/assets/113192435/262fc687-e837-4b04-a3ab-6b6a8718cb33)

related: should we lower this threshold to 50mb or 100mb?

**Comment by jawndiego** [comment]
PR #480

**Comment by salieflewis** [comment]
Resolved #480
