### ISSUE TITLE
Improve error handling in upload process (esp. large files + mux)

### ISSUE THREAD

**Issue by 0xTranqui** [1ifeworld/river#468]
27MB video upload failed a few times in poor connection envionrment (greyhound bus hotspot)

**Comment by salieflewis** [comment]
How can we turn this issue into something more actionable?

**Comment by 0xTranqui** [comment]
> How can we turn this issue into something more actionable?

maybe its more like: improve error handling in upload process? particularly for large files + files getting sent to mux + when in low connectivity environments

**Comment by jawndiego** [comment]
open PR on #479

**Comment by salieflewis** [comment]
> open PR on #479

How are the errors that bubble up on the media service reflected on the client?

**Comment by salieflewis** [comment]
Resolved #479
