### ISSUE TITLE
Unexpected behavior (for user): clicking the info tab stops the song im playing

### ISSUE THREAD

**Issue by 0xTranqui** [1ifeworld/river#471]
<img width="1512" alt="Screenshot 2024-02-12 at 11 03 15 AM" src="https://github.com/1ifeworld/river/assets/93691906/84be53c2-6759-4ad7-bb7e-0f5a2a67a1f4">

this makes sense this happens structurally, but in terms of user experience is weird. as a user, i obvi want to be able to click the "info" tab to see more about the piece im listening to, without it stopping my playback. not sure how to make this into a more actionable issue @salieflewis bc I imagine fixing this would require some level of restructuring data flows

cc @ioeylim for this weird ux

**Comment by salieflewis** [comment]
I actually did not experience this on Arc or Safari which is odd. Did this change at all with the new player?

**Comment by ioeylim** [comment]
> I actually did not experience this on Arc or Safari which is odd. Did this change at all with the new player?

Just tried on desktop/mobile safari and experienced the playback issue

**Comment by jawndiego** [comment]
clicking 'info' triggers an entire page refresh across players/renderers

**Comment by ioeylim** [comment]
resolved with #531
