### ISSUE TITLE
Add a vertical divider between the "media" and "index/info" containers

### ISSUE THREAD

**Issue by ioeylim** [1ifeworld/river#474]
<img width="1728" alt="Screenshot 2024-02-12 at 1 16 11 PM" src="https://github.com/1ifeworld/river/assets/113192435/464ccbec-9cda-4fd3-8f26-69ef3bb3fb21">

<img width="1601" alt="Screenshot 2024-02-12 at 1 23 33 PM" src="https://github.com/1ifeworld/river/assets/113192435/27e10973-1b5c-4b34-b068-8f9b7d14d917">

**Comment by salieflewis** [comment]
I think this is specifically when rendering markdown.

**Comment by ioeylim** [comment]
> I think this is specifically when rendering markdown.

Yeah it's only a visible issue for markdown – how do you like it for other types?
![Group 686](https://github.com/1ifeworld/river/assets/113192435/1d438a02-8761-42db-9d58-8a1bd71df8f4)

**Comment by salieflewis** [comment]
> > I think this is specifically when rendering markdown.
> 
> Yeah it's only a visible issue for markdown – how do you like it for other types? ![Group 686](https://private-user-images.githubusercontent.com/113192435/304197074-1d438a02-8761-42db-9d58-8a1bd71df8f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4Mzg2MDIsIm5iZiI6MTcwNzgzODMwMiwicGF0aCI6Ii8xMTMxOTI0MzUvMzA0MTk3MDc0LTFkNDM4YTAyLTg3NjEtNDJkYi05ZDU4LThhMWJkNzFkZjhmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxNTMxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2RkYzM5MzRhNjU0YmNlMzRmNjdhMmQ3MzYzN2M3OWRkZGE1ZWEwNDA2MjY4YWUyOGZiYWRlZWJkYjljZjNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DNhwZlgMRyV4kR4hAlLqM6ykVTPHvcEtWpP0e1jAwfg)

I see what you're saying. Yeah happy to include it universally, it is a nice divide.
