### ISSUE TITLE
Integrate authentication into the sidebar

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#48]
Similar to how avatars are displayed on [read.cv](https://read.cv/explore) it would be interesting to explore what having auth tucked into our sidebar would do for freeing up available space in the content section.

**Comment by ioeylim** [comment]
I was initially not really for it (mostly because moving auth to bottom left feels kinda weird for user security confidence vibes) but I think it could be really nice actually. down to explore this more

**Comment by salieflewis** [comment]
> I was initially not really for it (mostly because moving auth to bottom left feels kinda weird for user security confidence vibes) but I think it could be really nice actually. down to explore this more

I feel like I knew this, but also maybe it was abundantly clear and I just came across it again while reading the docs, but ConnectKit exposes a nice little avatar component :)

https://docs.family.co/connectkit/api-reference#additional-components-avatar

**Comment by salieflewis** [comment]
Updated the title name. Main questions are:

1. What is the default for users who don't have an ENS avatar?
2. What does this look like when you're not authenticated?
3. What does this look like when the sidebar is closed?
4. What does this look like on mobile?

**Comment by salieflewis** [comment]
Resolved #139
