### ISSUE TITLE
Solve unstable channel indices 

### ISSUE THREAD

**Issue by 0xTranqui** [1ifeworld/river#498]
<img width="597" alt="Screenshot 2024-02-20 at 8 54 26 AM" src="https://github.com/1ifeworld/river/assets/93691906/9e4978cb-9305-4e7e-bdbc-fe965c0017ef">

TLDR: I noticed a link I sent someone from River wip wasnt pointing at the correct item anymore. digging into why this is, I believe its because the "getChannelWithId" query we use to fetch data for the item page only returns the most recent 50 items. that means if your channel has more than 50 items, the order will start moving off by 1 for each additional item you are adding

My hunch is that this may be solved by some ocmbination of more sophistacated graphql fetching (cursor pagination for all adds) and better data structures in Delta

**Comment by ioeylim** [comment]
Resolved with #575
