### ISSUE TITLE
Integrate Vercel Analytics into the frontend

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#5]

**Comment by salieflewis** [comment]
Didn't realize this incurred an additional cost. I believe if we exceed a certain amount of events it gets tacked onto our bill. So maybe we will revisit this when we're already paying for Vercel, integrating it now is kind of confusing given we're on a trial.

https://vercel.com/docs/analytics

**Comment by 0xTranqui** [comment]
@salieflewis can we close this? or is this the type of thing we should keep open forever

**Comment by salieflewis** [comment]
> @salieflewis can we close this? or is this the type of thing we should keep open forever

I was sad I even opened it. I think we should look into potential alternatives/get more clarity when we're no longer on the trial. I remember saving an analytics alternative (alternative to Google and Vercel) on my phone somewhere that I'll look for. Not pressed to close this though.
