### ISSUE TITLE
Remove "50" item limit on channel page

### ISSUE THREAD

**Issue by ioeylim** [1ifeworld/river#509]
Channels affected: 
https://www.river.ph/channel/bafyreianhf3juz2wvo2lafnphepdgjyhjeqeppts7zqgkotgtd765kbo3q
https://www.river.ph/channel/bafyreihxse6bf2ne7cpfw6xybueny64zd7ni657juya3pwupot4fxiew3a

**Comment by ioeylim** [comment]
https://www.river.ph/channel/bafyreihuskbd64blgyd6lkx7es4boxljbdqp3w5s5d2sym5ovbergxjlna/6

"Communicate channel storage limits, not entirely sure the video upload limits are either but I definitely can’t upload another over 1 minute. 

When the channel limits are hit where do my files go? They just disappear into the abyss."

**Comment by salieflewis** [comment]
Resolved #552
