### ISSUE TITLE
Implement a color system

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#51]
So far, and for the demo as well, when there is a new hex code, I go and grab the name of it from [color-name.com](https://www.color-name.com/) and add that to the tailwind config.

This works for small apps, and you can create memorable little snippets of colors, but I'm not sure how well it scales for larger apps.

The one big issue is that it doesn't give us an idea of the relationship colors have to one another.

I haven't looked at this much, but like most things by the Radix team, [this](https://www.radix-ui.com/colors) is probably worth looking into.

**Comment by ioeylim** [comment]
the radix color chart is cool. we should definitely do a smaller scale version of that to cover all the hover/active state button colors, text colors, and etc. 

I'm kinda liking the current approach which is 4-5 monochromatic shades of grey, and the blue(can be anything else tho) accent color.

**Comment by salieflewis** [comment]
Dropping links to stylesheets/tailwind configs

shadcn: https://github.com/1ifeworld/river/blob/main/apps/frontend/styles/globals.css
entropy-dsl: https://github.com/calebguy/entropy-web/blob/main/packages/tailwind-config/tailwind.config.js
zord stylesheet: https://github.com/ourzora/nouns-builder/blob/main/packages/zoralabs-zord/src/tokens/color.ts

**Comment by salieflewis** [comment]
Resolved #126
