### ISSUE TITLE
Add a "processing, check back later" state to video/audio item pages

### ISSUE THREAD

**Issue by 0xTranqui** [1ifeworld/river#514]
It took 10 minutes from adding this item to being able to play it (bc of delay in mux processing -- 100MB file). I believe mux offers an endpoint to hit that returns the current processing state, that we could fetch in the server comp to know whether to show the player or not. i believe this was present in the Video class that we didnt end up ising, but presumabely the Assets class should let u find this as well

**Comment by ioeylim** [comment]
Resolved with #546
