### ISSUE TITLE
Add the ability to create public channels

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#516]
We've defined public channels as channels that any River user can add to. As far as the protocol goes, we've yet to explicitly declare the logic that will facilitate this. 

A public channel can be defined by a channel where rid 0 is part of the admins array. We can create a helper in delta which performs this check, ensuring that messages like `ADD_ITEM_TO_CHANNEL` are updated accordingly. 

Can you provide some color on this @0xTranqui, am I misremembering anything from the brief exchange we had about this.

**Comment by 0xTranqui** [comment]
working idea
- public channel = still controlled by admin (who remove public status, do content mod, etc) but anyone can post in it
- at protoocl level, this will be enabled by the admin giving RID #0 (no one has this) the role of `1`.
- presumabely need a bunch of new design to make this click as well cc @ioeylim

**Comment by salieflewis** [comment]
Resolved #525
