### ISSUE TITLE
Add anti-aliasing for fonts

### ISSUE THREAD

**Issue by ioeylim** [1ifeworld/river#52]
https://www.educative.io/answers/what-is-font-smoothing-in-css

**Comment by salieflewis** [comment]
Can you double-check this is not being done automatically by Next? This feels like one of those things.

**Comment by salieflewis** [comment]
https://github.com/emilkowalski/sonner/blob/main/website/app/globals.css

**Comment by ioeylim** [comment]
have you tried this? feels like it's just  `-webkit-font-smoothing: antialiased;` which i did for the lifeworld site

**Comment by salieflewis** [comment]
> have you tried this? feels like it's just `-webkit-font-smoothing: antialiased;` which i did for the lifeworld site

I think I can add it directly into the design system via a CSS module, like so https://github.com/calebguy/entropy-web/blob/main/packages/dsl/src/Text/Text.module.css

**Comment by salieflewis** [comment]
Also related.

https://github.com/liabru/material-design-type/blob/master/style.css
