### ISSUE TITLE
Update the auth component to directly disconnect a user without opening another modal

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#54]
I'm moving the discussion from #50 to here because I don't think we should be in the habit of having unresolved conversation in closed PRs.

@0xTranqui mentioned that I could directly access this via wagmi's `useDisconnect` which I wasn't thinking of initially. This is what should be done.

As far as separating the `Connect` and `AuthDropdown` components, I made the conscious decision to keep them in one file specifically because I imagined that is the only place it would be being used, and I feel that it is a logical coupling. Happy to split them up though.

Link to [seeknoevil](https://github.com/0xTranqui/seeknoevil/blob/master/src/components/auth/Connect.tsx) custom connect implementation.

Use custom `shortenAddress` util instead of ConnectKit's `truncatedAddress` helper.

cc: @0xTranqui @ioeylim

**Comment by ioeylim** [comment]
The dots feel a little bit jarring, but it's looking very good

<img width="147" alt="Screenshot 2023-08-29 at 11 36 41 AM" src="https://github.com/1ifeworld/river/assets/113192435/372f7fb0-b1ae-4119-b550-504ab6c85c55">
