### ISSUE TITLE
Add mux processing status tracking to media server

### ISSUE THREAD

**Issue by 0xTranqui** [1ifeworld/river#547]
rough sketch:

In this [route](https://github.com/1ifeworld/media-service/blob/main/routes/mux/upload.ts), do the following
- for all mux uploads, set the a new variable called "processing". this will always be set to true at the beginning
- once the upload is "set", then start another await/promise that will wait to get the result of the processing, and then update the "processing" field to either be "ready" or "error".

this will make it so we dont have to add item specific lookups for their processing state into the site, saving load times (since they can live in the media server

**Comment by jawndiego** [comment]
new issue: 

https://github.com/1ifeworld/media-service/issues/18
