### ISSUE TITLE
Update the factory address used by the `LightSmartContractAccount` class

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#59]
This should be replaced with the address of our custom factory, the address of which should be declared in the constants directory.

**Comment by salieflewis** [comment]
Wasn't sure if it was there or not/whether or not it makes sense for it to be there. But if it's already there then perfect.

**Comment by 0xTranqui** [comment]
can we close this @salieflewis ?

**Comment by salieflewis** [comment]
It has yet to be completed.

**Comment by 0xTranqui** [comment]
ok. are u down to assign this to yourself as part of finishing the username flow? if it ends up being more than just swapping out the address with the one exported from `scrypt`, then perhaps worthy of a larger issue?

**Comment by salieflewis** [comment]
The msg.sender of the register call is the address of the newly deployed Light Account. Do we still need to index the factory? If not, we no longer need our own modified implementation. Am I missing something?

cc: @0xTranqui @jawndiego
