### ISSUE TITLE
Integrate metadata processing 

### ISSUE THREAD

**Issue by jawndiego** [1ifeworld/river#62]
process alchemy return into new shape
`const contentObject = { pieceName, pieceCreator, pieceDescription, pieceImageURL, pieceAnimationURL, pieceCreatedDate, pieceContentType }`

**Comment by salieflewis** [comment]
Do we need this `piece` prefix on all of these objects?

cc: @jawndiego

**Comment by 0xTranqui** [comment]
> Do we need this `piece` prefix on all of these objects?
> 
> cc: @jawndiego

i think we can drop the 'piece' prefix -- although would point out that we need to be able to distinguish between channel name/creator/descrioption + listingTarget name/creator/description etc

**Comment by jawndiego** [comment]
i'm going to keep it for now until we figure out a good way to distinguish. once the process is working i can remove prefix and  add a better way to distinguish. wont push to main until this is figured out

**Comment by salieflewis** [comment]
Resolved #71
