### ISSUE TITLE
Integrate Metadata Token Storing 

### ISSUE THREAD

**Issue by jawndiego** [1ifeworld/river#63]
full crud process:
-listen for data stored
-decode data stored into listings array
-for each listing in array, fetch the target metadata
-process the metadata into our own shape
-append target metadata into same row as the listing, under the field” listingTargetMetadata”

metadata mock shape: 

- type Metadata https://github.com/entity {
unique Id `${networkId!}${targetAddress!}${targetID?}
pieceName:
pieceCreator:
pieceDescription:
pieceImageURL:
pieceAnimation_URL: pieceCreatedDate:
pieceContentType:
}

type Listing https://github.com/entity {
x
X
X
X
targetMetadata: [Metadata!] @derivedFrom
}

**Comment by salieflewis** [comment]
Resolved #71
