### ISSUE TITLE
Create `AddToChannel` Modal

### ISSUE THREAD

**Issue by 0xTranqui** [1ifeworld/river#64]
This modal is a multi functional component that will allow users to access `AddToChannel` functionality. Although the iniitial implementation will only provide the ability to look existing things up on ethereum mainnet and bring them in, it will be constructed to support the toggling between other functionality as well such as uploading a new file directly or opening up a text edtior

**Comment by salieflewis** [comment]
Figma: https://www.figma.com/file/vq8D56Fddhysfv24raCmL1/River?type=design&node-id=91%3A4157&mode=design&t=5x4un5ikJ4laqylV-1
