### ISSUE TITLE
Revisit filtering

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#72]
- [ ] Determine if filters need to be added to any of the remaining CRUD processes

Node Registry CRUD is crudely done

**Comment by 0xTranqui** [comment]
all of the access control + logic of how we want things to work are NOT implemented yet. can you be more clear about what you mean by filtering? filtering as in search? or as in moving the CRUD closer to its final verison?

**Comment by salieflewis** [comment]
> all of the access control + logic of how we want things to work are NOT implemented yet. can you be more clear about what you mean by filtering? filtering as in search? or as in moving the CRUD closer to its final verison?

Borrowed this language from @jawndiego so I'm going to leave it to him to flesh this out.

**Comment by jawndiego** [comment]
moving crud closer to final version

**Comment by salieflewis** [comment]
Can we get an update on this @jawndiego

**Comment by 0xTranqui** [comment]
@salieflewis can we close this
