### ISSUE TITLE
Add the ability to create channels via the `ChannelDialog`

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#76]
If we're saying in #73 that having existing channels is necessary to then create publications, facilitating the creation of channels seems like it should come first. So the most rudimentary form of creating a channel is essentially what is shown below.

![CleanShot 2023-11-15 at 11 29 48@2x](https://github.com/1ifeworld/river/assets/37086973/ca985bde-23db-4d46-ba73-fc9a4de13629)

So I'm suggesting we implement a flow where users can create channels without the ability to add a cover image or description. These channels should then show up on the homepage, and in order to do that we'll need to complete #75 

- [x] Create a new server action called `createChannel` and connect it to the `ChannelDialog`
- [x] On successful completion, close the dialog and provide user feedback that the channel has been created via a toast #61

Currently we're hardcoding the JSON object that is getting written to IPFS, we need to stringify the blob that is coming through the form and pass this to the `uploadBlob` call.

**Comment by 0xTranqui** [comment]
This sounds great to me! simple channels otw

**Comment by salieflewis** [comment]
Resolved #87 #100
