### ISSUE TITLE
Optimize `DataSent` event handler

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#77]
Pulled from comments on #71 

There could be one optimization in `DataSent` that enables us to avoid fetching target nft metadata for a listing if we've already fetched it before -- by moving the code related to the fetching of the metadata underneath the if check if that listing id (network/targetAddress/id) has already been added.

**Comment by jawndiego** [comment]
addressed in [dc0ea5c](https://github.com/1ifeworld/river/commit/dc0ea5c34e12010664dadd691bf451b2d97f109d)
