### ISSUE TITLE
Implement Rudimentrary User Activity Page

### ISSUE THREAD

**Issue by 0xTranqui** [1ifeworld/river#77]
<img width="828" alt="Screenshot 2023-11-15 at 12 49 19 PM" src="https://github.com/1ifeworld/river/assets/93691906/09f8a118-5f8e-4eef-a2cf-0a23086fdcec">

Scope:
- [ ] add new route to site (looking like river.ph/{username / .eth} for now
- [ ] figure out how to add in a username description field (where does data live at protocol level)
- [ ] pull in all channels a user is an admin/member on and represent them visually
- [ ] pull in all items a user has created and represent them visually
- [ ] needs to update live everytime an update occurs

**Comment by salieflewis** [comment]
Resolved #85
