### ISSUE TITLE
Update the `UsernameDialog` to fetch the new user's `userId` from our Ponder database

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#79]
Currently the way we're determining the `userId` of a new user during the onboarding flow is by waiting for the logs of the registration call to come in and grabbing said data like that. This is inconsistent and should be handled with a direct database lookup. Are the CRUD actions/indexing in place for us to do this?

cc: @jawndiego @0xTranqui 

- [ ] Write a query that grabs a user's id based on their smart account address
_Will this lookup actually be backup address to userId? If so could that be problematic in the future?_
- [ ] Implement a respective getter 
- [ ] Replace the `getLogs` call with this data and ensure the `setUsername` request doesn't get triggered until the data is returned and is valid

**Comment by salieflewis** [comment]
Realizing that backup is not what I'm referring to.

**Comment by jawndiego** [comment]
Jawn/issue79 #84 closes this
