### ISSUE TITLE
Adapt our database schema from Prisma to Ponder

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#8]
We should include documentation somewhere about how our Ponder schema works such that it can be adapted easily as the protocol changes.

**Comment by salieflewis** [comment]
> first try @ jawn/i#8_graphql

You should open a pull request against your branch, save it as a draft, and then tag the issue

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by salieflewis** [comment]
Resolved.

**Comment by jawndiego** [comment]
re-opening for the following reasons: 

1. need to create composite IDs for Token Storage (press address + tokenID). The reason for this is that for events like press data updated we will always encounter a unique id error if we only use press address as id. specifically for events like this we need to specify a combination of shared press address and a unique token id. 
2. need to find the common fields between all events and make those required (!). make the rest optional.
3. need to refigure the schema to fit the most up to date protocol.

**Comment by salieflewis** [comment]
Resolved #36
