### ISSUE TITLE
Split out all event cruds into their own files in Delta

### ISSUE THREAD

**Issue by 0xTranqui** [1ifeworld/river#81]
<img width="222" alt="Screenshot 2023-11-15 at 2 39 15 PM" src="https://github.com/1ifeworld/river/assets/93691906/b0ca0fa5-3a65-48e4-88c5-5e3083f89158">

tldr moving to a new structure in delta where instead of keeping all event cruds for a contract in one file named {ContraName}.ts, introduce a folder structure where folder = {ContractName}, and one {EventName}.ts is created to house each crud event for that contract. see screenshot for inspo. the contracts we want to do this for are:

- idRegistry
- delegateRegistry (there is no more transfer nonce anymore, just a heads up. plz check solidity before re implementing)
- attestationRegistry
- nodeRegistry
- riverValidatorV1
- LightAccountFactory

**Comment by salieflewis** [comment]
Resolved #91
