### ISSUE TITLE
Update the add to channel modal to be responsive

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#82]
Perhaps also including some version of this menu component in conjunction with the code that we already have for navigating between Upload, Search, and Text

https://github.com/ourzora/nouns-marketplace/blob/main/components/HorizontalMenu/HorizontalMenu.tsx

Also looking at this again @ioeylim, Upload and Search are both verbs while Text is a noun. Maybe this becomes Write?

**Comment by ioeylim** [comment]
yes, let's change it to write.

**Comment by salieflewis** [comment]
Resolved #261
