### ISSUE TITLE
Create the foundations of the design system

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#90]
I'll create smaller tasks within this issue as we build towards a rudimentary design system

- [x] Rename the `base` directory to `elements` and include layout components like `Stack` 
- [x] Create a Next.js playground for the design system inside our `apps` directory
- [x] Rename the design system itself, the package should appear as `@river/estuary`

cc: @ioeylim

**Comment by salieflewis** [comment]
In regards to icons, it looks like what Mirror does, is import the actual svg files, and then run a generate script which leverages [this](https://www.npmjs.com/package/@svgr/core) to turn those files into React components.

**Comment by ioeylim** [comment]
This is all great!! I'm excited for this

**Comment by salieflewis** [comment]
Resolved #91
