### ISSUE TITLE
Make a new request to the server after adding a listing to a channel

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#92]
Channel data is being pulled in via an asynchronous `getChannel` call. This occurs within our channel route.

We can use Next's router API and programmatically refresh (`router.refresh()`) the route via some sort of callback from our `Add` (to channel) function.

https://nextjs.org/docs/app/api-reference/functions/use-router

For some reason I thought you may be able to achieve all this within a server component, but it looks like the only access to the router API is via a hook, so doesn't look like that is the case.

Either way there is [a way of doing this](https://github.com/dijonmusters/build-a-twitter-clone-with-the-next.js-app-router-and-supabase/blob/941ae910701d32eebd2e3e3e77ed525dfd22ca28/16-declare-global-union-types-with-typescript/app/likes.tsx#L24) that avoids using a `useEffect` hook which is nice because I think it preserves state. 

Honestly not even sure if `useEffect` does not preserve browser state.

cc: @0xTranqui

**Comment by 0xTranqui** [comment]
The thing im thinking of is that we want whats happening on one persons instance of river to also show up on other ppls instance of river. ex: im on the lifeworld channel and 4 pieces, i would want someone else also on the lfieworld channel at the same time to see those 4 pieces added

**Comment by 0xTranqui** [comment]
just had a good [back and forth](https://chat.openai.com/share/dffdd8cb-ebd1-4dff-be91-68288f485a9e) with chat gpt about this and it set websockets are the way. is there a reason you are opposed to that general direction?

**Comment by 0xTranqui** [comment]
the tldr of that back and forth is

1. setup web socket server
2. server component (channel grid) streams in data from websocket
3. client component (add to channel button) pings websocket to refresh when it processes a transaction
4. server component re renderes on new data

**Comment by salieflewis** [comment]
Doesn't seem like #93 solved this issue.

**Comment by salieflewis** [comment]
The issue here seems to be that the `OnSuccess` callback from `useWaitForTransaction` doesn't seem to be getting triggered consistently.

**Comment by salieflewis** [comment]
As of Friday, September 8th, this was working just fine. Wonder if we can close this, but that doesn't explain periods where it was acting up.
