### ISSUE TITLE
Update activity page so it takes in live data

### ISSUE THREAD

**Issue by 0xTranqui** [1ifeworld/river#97]
TLDR: right now river.ph/{username} is displaying a view with mock data thats been hardcoded

Scope: update that view to ingest actual data. may require some new queries + re working of ponder entity table + crud, but might be ok already by writing a more complex query based off current data to get user filtered data

cc @jawndiego for vis -- will let u know if I have to go into delta at all

**Comment by salieflewis** [comment]
I don't think these queries are quite there, and I removed them cause they were causing issues with the codegen process. But pasting here so you don't need to rewrite the getter.

https://gist.github.com/salieflewis/b1b9a0ef5bbf42e89a85bdf3c4134163

cc: @0xTranqui

**Comment by salieflewis** [comment]
Resolved in favor of #436
