### ISSUE TITLE
Introduce a 404 page

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#98]

**Comment by ioeylim** [comment]
<img width="1279" alt="Screenshot 2023-09-01 at 6 05 44 PM" src="https://github.com/1ifeworld/river/assets/113192435/768c4dae-0be0-486c-ad98-2801bf377b9f">

anyone got some creative ideas??

@1ifeworld/core

**Comment by salieflewis** [comment]
Spent some time trying to get this SVG to be responsive regardless of the sidebar, but was running into some issues even with just that. I'm not really certain how to pass in props to the SVG conditionally given the `not-found` component is server side. And I don't want to make it client side because it causes issues up the tree.

Made a discussion post here on the Next forum related to this: https://github.com/vercel/next.js/discussions/55984

**Comment by salieflewis** [comment]
Resolved #274
